[[headers]]
  for = "/*.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://demo3121.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Max-Age = "300"
